name: Redraw graph

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Draw graph
        run: python draw.py

      - name: Commit updated graph back to the repo
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update graph'
          add: 'Graphs/*.png'
